### ISSUE TITLE
modeltime.ensemble removed from cran

### ISSUE THREAD

**Issue by gbgoutha** [business-science/modeltime.ensemble#29]
Hi,

Thank you for your work on this package. The package is removed from CRAN. Also, can't install dev version from github. Is there an expected time at which it will be available there again? We have a dependency on this package to run our forecast pipeline weekly.

Thanks.

**Comment by mdancho84** [comment]
I'm planning to do some work this weekend. In the meantime I'd suggest installing via GitHub or cloning the repo and installing it locally. 

CRAN kicked it off for a minor test issue so my hope is it doesn't take long. But you never know with the submission process. So plan accordingly.

**Comment by mdancho84** [comment]
Finally... Back on CRAN.
