### ISSUE TITLE
Ensemble Model Spec example code causes an error

### ISSUE THREAD

**Issue by schwarzpat** [business-science/modeltime.ensemble#30]
I have been running the code chunk from
https://business-science.github.io/modeltime.ensemble/reference/ensemble_model_spec.html and i get this error at ensemble_fit_glmnet <- submodel_predictions %>%
    ensemble_model_spec(
        model_spec = linear_reg(
            penalty = tune(),
            mixture = tune()
        ) %>%
            set_engine("glmnet"),
        grid       = 2,
        control    = control_grid(verbose = TRUE)
    )

`
── Tuning Model Specification ───────────────────────────────────
ℹ Performing 5-Fold Cross Validation.

Error in `tune::show_best()`:
! `...` must be empty.
✖ Problematic argument:
• ..1 = metric
ℹ Did you forget to name an argument?
Backtrace:
 1. submodel_predictions %>% ...
 7. tune:::show_best.tune_results(., metric, n = 1)`

presumably this is because a deprecation in tune a while ago.

**Comment by mdancho84** [comment]
Should be fixed now
